app = "keepup-backend"
primary_region = "iad"

[build]
  dockerfile = "backend/Dockerfile"

[env]
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_start_machines = true
  auto_stop_machines = true
  min_machines_running = 0
  processes = ["app"]

  [http_service.concurrency]
    type = "requests"
    hard_limit = 50
    soft_limit = 25

[[vm]]
  size = "shared-cpu-1x"
  memory = "256mb"

[[services.tcp_checks]]
  interval = "15s"
  timeout = "2s"
  grace_period = "10s"
  restart_limit = 0



